import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarController from "./components/sidebar/controller";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          {/* Sidebar: fixed height, no scroll */}
          <div className="h-screen sticky top-0">
           <SidebarController />
          </div>

          {/* Main content scrolls independently */}
          <div className="flex-1 overflow-y-auto p-6 h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}